version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
      - "3000:4000" 
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets 
    depends_on:
      - php
    networks:
      - app-network
    
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: yii2app
      MYSQL_USER: yii2user 
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "33062:3306"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
